package com.mzaragozaserrano.domain.bo

data class AdBO(
    val address: String? = null,
    val bathrooms: Int? = null,
    val country: String? = null,
    val date: String? = null,
    val description: String? = null,
    val district: String? = null,
    val exterior: String? = null,
    val features: FeaturesBO? = null,
    val floor: String? = null,
    var isFavorite: Boolean = false,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val multimedia: MultimediaBO? = null,
    val municipality: String? = null,
    val neighborhood: String? = null,
    val operation: String? = null,
    val parkingSpace: ParkingSpaceBO? = null,
    val price: Double? = null,
    val priceInfo: PriceInfoBO? = null,
    val propertyCode: String? = null,
    val propertyType: String? = null,
    val province: String? = null,
    val rooms: Int? = null,
    val size: Double? = null,
    val thumbnail: String? = null,
)
